### ISSUE TITLE
Better rendering for aligned text

### ISSUE THREAD

**Issue by martinheidegger** [pastak/html2sb-compiler#3]
In evernote it is possible to align text like this:
![https://gyazo.com/c8490f6871d8c9f867c728c033bf71c9](https://i.gyazo.com/c8490f6871d8c9f867c728c033bf71c9.png)

Currently this is rendered like 
![https://gyazo.com/b1cb326c6204c11361b92e17a3bd79a3](
https://gyazo.com/b1cb326c6204c11361b92e17a3bd79a3.png)

which is very hard to read.

**Comment by pastak** [comment]
This is high priority thing I think.

**Comment by martinheidegger** [comment]
Closed in #4
